---
- name: Check if theme directory exists and is not empty
  ansible.builtin.find:
    paths: "{{ item.install_dir }}"
    file_type: any
  register: theme_dir_content
  loop: "{{ redmine_themes }}"
  loop_control:
    loop_var: item

- name: Install themes if directory is empty or does not exist
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.install_dir }}"
    version: "{{ item.version }}"
  loop: "{{ redmine_themes }}"
  loop_control:
    loop_var: item
  when: theme_dir_content.results[loop.index0].files | length == 0

- name: Add ui_theme setting to configuration.yml
  become: yes
  ansible.builtin.blockinfile:
    path: "{{ redmine_dir }}/config/configuration.yml"
    block: |
      ui_theme: '{{ redmine_theme }}'
    insertafter: "^production:"

- name: Clear Redmine cache
  ansible.builtin.command:
    cmd: bundle exec rake tmp:cache:clear
    chdir: '{{ redmine_dir }}'
  changed_when: false

- name: Restart Redmine
  ansible.builtin.command:
    cmd: touch tmp/restart.txt
    chdir: '{{ redmine_dir }}'
  changed_when: false
