---
- name: Check if theme directory exists
  ansible.builtin.stat:
    path: "{{ item.install_dir }}"
  register: theme_dir_result
  loop: "{{ redmine_themes }}"
  loop_control:
    loop_var: item

- name: Install themes if not already present
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.install_dir }}"
    version: "{{ item.version }}"
  loop: "{{ redmine_themes }}"
  loop_control:
    loop_var: item
  when: not item.install_dir is in theme_dir_result.results | map(attribute='stat.exists') | list

- name: Add ui_theme setting to configuration.yml
  become: yes
  ansible.builtin.blockinfile:
    path: "{{ redmine_dir }}/config/configuration.yml"
    block: |
      ui_theme: '{{ redmine_theme }}'
    insertafter: "^production:"

- name: Clear Redmine cache
  ansible.builtin.command:
    cmd: bundle exec rake tmp:cache:clear
    chdir: '{{ redmine_dir }}'
  changed_when: false

- name: Restart Redmine
  ansible.builtin.command:
    cmd: touch tmp/restart.txt
    chdir: '{{ redmine_dir }}'
  changed_when: false
