---
- name: Check if theme directory exists
  ansible.builtin.stat:
    path: "{{ item.install_dir }}"
  register: theme_dir
  with_items:
    - "{{ redmine_themes }}"

- name: Install themes if not already present
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.install_dir }}"
    version: "{{ item.version }}"
  with_items:
    - "{{ redmine_themes }}"
  when: not theme_dir.stat.exists

- name: Add ui_theme setting to configuration.yml
  become: yes
  ansible.builtin.blockinfile:
    path: "{{ redmine_dir }}/config/configuration.yml"
    block: |
      ui_theme: '{{ redmine_theme }}'
    insertafter: "^production:"

- name: Clear Redmine cache
  ansible.builtin.command:
    cmd: bundle exec rake tmp:cache:clear
    chdir: '{{ redmine_dir }}'
  changed_when: false

- name: Restart Redmine
  ansible.builtin.command:
    cmd: touch tmp/restart.txt
    chdir: '{{ redmine_dir }}'
  changed_when: false
